steps:
  # Build the container image with caching
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/commerce-backend:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/commerce-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/commerce-backend:latest'
      - '.'

  # Push the container images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/commerce-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'commerce-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/commerce-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'CORS_ORIGINS=*'

images:
  - 'gcr.io/$PROJECT_ID/commerce-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/commerce-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
