services:
  - type: web
    name: commerce-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_server:app --workers 2 --threads 8 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://your-frontend-domain.vercel.app

