# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class AgentDirective(BaseModel):
    intent: typing.Optional[types.ConversationType] = None
    reply: typing.Optional[str] = None
    refined_query: typing.Optional[str] = None
    min_price: typing.Optional[float] = None
    max_price: typing.Optional[float] = None
    min_rating: typing.Optional[float] = None
    category: typing.Optional[str] = None

class ProductRecommendation(BaseModel):
    product_id: typing.Optional[str] = None
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    category: typing.Optional[str] = None
    price: typing.Optional[float] = None
    rating: typing.Optional[float] = None
    relevance_score: typing.Optional[float] = None
    reason: typing.Optional[str] = None

class SearchFilters(BaseModel):
    category: typing.Optional[str] = None
    min_price: typing.Optional[float] = None
    max_price: typing.Optional[float] = None
    min_rating: typing.Optional[float] = None

class UserQueryInput(BaseModel):
    user_message: typing.Optional[str] = None
    has_image: typing.Optional[bool] = None
    image_description: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
