# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AgentDirective": types.AgentDirective,
    "stream_types.AgentDirective": stream_types.AgentDirective,

    "types.ProductRecommendation": types.ProductRecommendation,
    "stream_types.ProductRecommendation": stream_types.ProductRecommendation,

    "types.SearchFilters": types.SearchFilters,
    "stream_types.SearchFilters": stream_types.SearchFilters,

    "types.UserQueryInput": types.UserQueryInput,
    "stream_types.UserQueryInput": stream_types.UserQueryInput,


    "types.ConversationType": types.ConversationType,

}